name: Generate Docs & Deploy
on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    generate_and_deploy:
        runs-on: ubuntu-latest
        name: Generate & deploy
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - name: Setup Node environment
              uses: actions/setup-node@v2
              with:
                  node-version: "14"

            - name: Install dependencies
              uses: bahmutov/npm-install@v1

            - name: Generate static Storybook site
              run: npm run ci:storybook:build

            - name: Generate Jest coverage report
              run: npm run ci:test

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@4.1.4
              with:
                  branch: gh-pages
                  folder: docs
